// 
// Decompiled by Procyon v0.6-prerelease
// 

package com.admarvel.android.ads;

public enum AdMarvelUtils$ErrorReason
{
    AD_REQUEST_IN_PROCESS_EXCEPTION("AD_REQUEST_IN_PROCESS_EXCEPTION", 11), 
    AD_REQUEST_MISSING_XML_ELEMENTS("AD_REQUEST_MISSING_XML_ELEMENTS", 13), 
    AD_REQUEST_SDK_TYPE_UNSUPPORTED("AD_REQUEST_SDK_TYPE_UNSUPPORTED", 14), 
    AD_REQUEST_XML_PARSING_EXCEPTION("AD_REQUEST_XML_PARSING_EXCEPTION", 10), 
    AD_UNIT_NOT_ABLE_TO_LOAD("AD_UNIT_NOT_ABLE_TO_LOAD", 15), 
    AD_UNIT_NOT_ABLE_TO_RENDER("AD_UNIT_NOT_ABLE_TO_RENDER", 12), 
    BOT_USER_AGENT_FOUND("BOT_USER_AGENT_FOUND", 2), 
    NETWORK_CONNECTIVITY_DISRUPTED("NETWORK_CONNECTIVITY_DISRUPTED", 9), 
    NO_AD_FOUND("NO_AD_FOUND", 4), 
    NO_BANNER_FOUND("NO_BANNER_FOUND", 3), 
    NO_NETWORK_CONNECTIVITY("NO_NETWORK_CONNECTIVITY", 8), 
    NO_USER_AGENT_FOUND("NO_USER_AGENT_FOUND", 5), 
    PARTNER_ID_NOT_PRESENT("PARTNER_ID_NOT_PRESENT", 7), 
    SITE_ID_AND_PARTNER_ID_DO_NOT_MATCH("SITE_ID_AND_PARTNER_ID_DO_NOT_MATCH", 1), 
    SITE_ID_NOT_PRESENT("SITE_ID_NOT_PRESENT", 6), 
    SITE_ID_OR_PARTNER_ID_NOT_PRESENT("SITE_ID_OR_PARTNER_ID_NOT_PRESENT", 0);
    
    private AdMarvelUtils$ErrorReason(final String s, final int n) {
    }
}
