// 
// Decompiled by Procyon v0.6-prerelease
// 

package com.admarvel.android.ads;

public enum AdMarvelUtils$AdMArvelErrorReason
{
    AD_REQUEST_IN_PROCESS_EXCEPTION("AD_REQUEST_IN_PROCESS_EXCEPTION", 11, 304), 
    AD_REQUEST_MISSING_XML_ELEMENTS("AD_REQUEST_MISSING_XML_ELEMENTS", 13, 306), 
    AD_REQUEST_SDK_TYPE_UNSUPPORTED("AD_REQUEST_SDK_TYPE_UNSUPPORTED", 14, 307), 
    AD_REQUEST_XML_PARSING_EXCEPTION("AD_REQUEST_XML_PARSING_EXCEPTION", 10, 303), 
    AD_UNIT_NOT_ABLE_TO_LOAD("AD_UNIT_NOT_ABLE_TO_LOAD", 15, 308), 
    AD_UNIT_NOT_ABLE_TO_RENDER("AD_UNIT_NOT_ABLE_TO_RENDER", 12, 305), 
    BOT_USER_AGENT_FOUND("BOT_USER_AGENT_FOUND", 2, 203), 
    NETWORK_CONNECTIVITY_DISRUPTED("NETWORK_CONNECTIVITY_DISRUPTED", 9, 302), 
    NO_AD_FOUND("NO_AD_FOUND", 4, 205), 
    NO_BANNER_FOUND("NO_BANNER_FOUND", 3, 204), 
    NO_NETWORK_CONNECTIVITY("NO_NETWORK_CONNECTIVITY", 8, 301), 
    NO_USER_AGENT_FOUND("NO_USER_AGENT_FOUND", 5, 206), 
    PARTNER_ID_NOT_PRESENT("PARTNER_ID_NOT_PRESENT", 7, 208), 
    SITE_ID_AND_PARTNER_ID_DO_NOT_MATCH("SITE_ID_AND_PARTNER_ID_DO_NOT_MATCH", 1, 202), 
    SITE_ID_NOT_PRESENT("SITE_ID_NOT_PRESENT", 6, 207), 
    SITE_ID_OR_PARTNER_ID_NOT_PRESENT("SITE_ID_OR_PARTNER_ID_NOT_PRESENT", 0, 201);
    
    private final int a;
    
    private AdMarvelUtils$AdMArvelErrorReason(final String s, final int n, final int a) {
        this.a = a;
    }
    
    public final int getErrorCode() {
        return this.a;
    }
}
